import { SiteChrome } from './SiteChrome.js';
import { BlogFeed } from './BlogFeed.js';
import { EventSchedule } from './EventSchedule.js';
import { CourseLibrary } from './CourseLibrary.js';
import { CourseCatalog } from './CourseCatalog.js';
import { QuantumCourse } from './QuantumCourse.js';
import { QuantumCourse2016 } from './QuantumCourse2016.js';
import { PowerElectronicsCourse } from './PowerElectronicsCourse.js';
import { NuclearEngineeringCourse } from './NuclearEngineeringCourse.js';
import { StanfordCme295Course } from './StanfordCme295Course.js';
import { YouTubePlaylistCourse } from './YouTubePlaylistCourse.js';
import { YalePhysicsCourse } from './YalePhysicsCourse.js';
import { MitLectureCourse } from './MitLectureCourse.js';
import { BlakeMortimerCatalog } from './BlakeMortimerCatalog.js';
import { ComicVolumeDetail } from './ComicVolumeDetail.js';
import { ShirowUniverse } from './ShirowUniverse.js';
import { ShirowWorkDetail } from './ShirowWorkDetail.js';
import { C64Games } from './C64Games.js';
import { C64Neuromancer } from './C64Neuromancer.js';
import { ActiveProjects } from './ActiveProjects.js';
import { IoTTopicPage } from './IoTTopicPage.js';
import { IndustrialIoTTopicPage } from './IndustrialIoTTopicPage.js';
import { JSONStructureTopic } from './JSONStructureTopic.js';
import { EmbeddedTopicPage } from './EmbeddedTopicPage.js';
import { PhilosophyTopicPage } from './PhilosophyTopicPage.js';
import { FilmPage } from './FilmPage.js';
import { StarTrekGuide } from './StarTrekGuide.js';

document.addEventListener('DOMContentLoaded', () => {
  new SiteChrome().init();
  new BlogFeed('#blog-post-list').init();
  new EventSchedule('#event-list').init();
  new CourseLibrary().init();
  new CourseCatalog().init();
  new QuantumCourse().init();
  new QuantumCourse2016().init();
  new PowerElectronicsCourse().init();
  new NuclearEngineeringCourse().init();
  new StanfordCme295Course().init();
  new YouTubePlaylistCourse().init();
  new YalePhysicsCourse().init();
  new MitLectureCourse().init();
  new BlakeMortimerCatalog().init();
  new ComicVolumeDetail().init();
  new ShirowUniverse().init();
  new ShirowWorkDetail().init();
  new C64Games().init();
  new C64Neuromancer().init();
  new ActiveProjects().init();
  new IoTTopicPage().init();
  new IndustrialIoTTopicPage().init();
  new JSONStructureTopic().init();
  new EmbeddedTopicPage().init();
  new PhilosophyTopicPage().init();
  new FilmPage().init();
  new StarTrekGuide().init();
});