export class ShirowWorkDetail {
  constructor() {
    this.root = document.querySelector('[data-shirow-work]');
    if (!this.root) return;
    this.key = this.root.dataset.shirowWork;
    this.work = this.works()[this.key];
  }

  init() { if (this.work) this.render(); }

  works() {
    const d = (title,year,kind,continuity,summary,themes,credits,source) => ({title,year,kind,continuity,summary,themes,credits,source});
    return {
      'black-magic':d('Black Magic','1983','Manga','Opera di Masamune Shirow','Nel pianeta Venere di un futuro remoto, scienza, magia e mitologia si sovrappongono. La raccolta d’esordio presenta Dee, Zeus e macchine autonome in racconti già ossessionati dal confine tra umano e artificiale.','IA, mitologia, robotica, potere','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Black_Magic_(manga)'),
      'appleseed':d('Appleseed','1985–1989','Manga · 4 volumi','Opera di Masamune Shirow','Dopo una guerra mondiale, Deunan Knute e il cyborg Briareos entrano a Olympus, città governata da bioroidi. L’utopia rivela tensioni tra sicurezza, libertà, terrorismo e gestione tecnocratica della società.','Utopia, politica, cyborg, mecha','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Appleseed_(manga)'),
      'dominion':d('Dominion','1986','Manga','Opera di Masamune Shirow','In una Newport avvolta da una nube batterica, la Tank Police combatte il crimine con mezzi sproporzionati. Leona, Bonaparte e le Puma Sisters trasformano il cyberpunk in commedia d’azione.','Ecologia, polizia, carri armati, satira','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Dominion_(manga)'),
      'black-magic-m66':d('Black Magic M-66','1986','Manga breve / OVA 1987','Opera di Masamune Shirow','Due androidi militari M-66 vengono attivati accidentalmente e seguono il loro programma di assassinio. La giornalista Sybel tenta di proteggere la giovane Ferris dalla macchina da guerra.','Androidi, automazione, caccia, responsabilità','Manga: Masamune Shirow · OVA: Shirow e Hiroyuki Kitakubo','https://en.wikipedia.org/wiki/Black_Magic_M-66'),
      'ghost-in-the-shell-manga':d('Ghost in the Shell','1989–1990','Manga','Continuità originale di Shirow','Nel XXI secolo iperconnesso, il maggiore Motoko Kusanagi guida la Sezione 9 contro terrorismo e crimini informatici. L’incontro con il Burattinaio mette in crisi la distinzione tra programma, persona e nuova forma di vita.','Identità, reti, coscienza, Stato','Testi e disegni: Masamune Shirow','https://it.wikipedia.org/wiki/Ghost_in_the_Shell'),
      'dominion-conflict-one':d('Dominion: Conflict One','1991','Manga','Opera di Masamune Shirow','Leona e la Tank Police tornano in una storia autonoma che amplia il conflitto politico ed ecologico di Newport, tra terrorismo, robot e rivalità dentro le forze dell’ordine.','Polizia, ecologia, mecha, commedia','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Dominion_(manga)'),
      'orion':d('Orion','1991–1996','Manga','Opera di Masamune Shirow','Nell’impero di Yamata, il mago Susano e la sacerdotessa Seska vengono coinvolti in un rituale cosmico. Tecnologia, formule taoiste e divinità si fondono in una science fantasy volutamente complessa.','Taoismo, cosmologia, magia, tecnologia','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Orion_(manga)'),
      'ghost-in-the-shell-1-5':d('Ghost in the Shell 1.5: Human-Error Processor','1991–1997','Manga · 4 episodi','Continuità originale di Shirow','Dopo gli eventi del primo volume, la Sezione 9 affronta sequestri, omicidi e complotti industriali. Togusa e il gruppo diventano protagonisti di un procedural corale.','Crimine informatico, investigazione, politica','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Ghost_in_the_Shell_1.5:_Human-Error_Processor'),
      'ghost-in-the-shell-2':d('Ghost in the Shell 2: Man-Machine Interface','1997–2001','Manga','Continuità originale di Shirow','Motoko Aramaki, entità nata dall’evoluzione del Maggiore, opera simultaneamente attraverso corpi remoti. Un’indagine industriale diventa scontro tra intelligenze distribuite e coscienze emergenti.','Postumano, IA, identità distribuita, rete','Testi e disegni: Masamune Shirow','https://en.wikipedia.org/wiki/Ghost_in_the_Shell_2:_Man-Machine_Interface'),
      'ghost-in-the-shell-1995':d('Ghost in the Shell','1995','Film anime','Continuità cinematografica di Oshii','Motoko insegue il Puppet Master, hacker capace di manipolare memorie. La scoperta che si tratta di una vita nata nella rete conduce il Maggiore verso una fusione evolutiva.','Coscienza, corpo, memoria, evoluzione','Regia: Mamoru Oshii · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell_(1995_film)'),
      'ghost-in-the-shell-2-innocence':d('Ghost in the Shell 2: Innocence','2004','Film anime','Continuità cinematografica di Oshii','Batou e Togusa indagano su ginoidi domestiche che uccidono i proprietari. L’assenza-presenza di Motoko accompagna una riflessione su bambole, animali, corpi e anime.','Ginoidi, anima, simulacro, memoria','Regia: Mamoru Oshii · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell_2:_Innocence'),
      'ghost-in-the-shell-2-0':d('Ghost in the Shell 2.0','2008','Film anime · revisione','Continuità cinematografica di Oshii','Nuova versione del film del 1995 con color grading rivisto, audio rielaborato, nuovo doppiaggio giapponese e sequenze sostituite da CGI. La storia resta sostanzialmente invariata.','Restauro, CGI, identità, rete','Regia: Mamoru Oshii · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell_(1995_film)'),
      'stand-alone-complex':d('Ghost in the Shell: Stand Alone Complex','2002–2003','Serie TV · 26 episodi','Continuità Stand Alone Complex','La Sezione 9 affronta casi autonomi e il complesso caso dell’Uomo che Ride, nato da corruzione farmaceutica e copie senza originale.','Memetica, politica, sorveglianza, rete','Regia: Kenji Kamiyama · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_Stand_Alone_Complex'),
      'stand-alone-complex-2nd-gig':d('Stand Alone Complex 2nd GIG','2004–2005','Serie TV · 26 episodi','Continuità Stand Alone Complex','La crisi dei rifugiati e gli Undici Individuali oppongono la Sezione 9 a un piano geopolitico guidato da Kazundo Gōda.','Rifugiati, nazionalismo, terrorismo, memi','Regia: Kenji Kamiyama · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_S.A.C._2nd_GIG'),
      'solid-state-society':d('Solid State Society','2006','Film TV anime','Continuità Stand Alone Complex','Due anni dopo 2nd GIG, Togusa guida una Sezione 9 ampliata. Il caso di bambini rapiti e anziani connessi conduce a un nuovo Burattinaio e al ritorno di Motoko.','Welfare, infanzia, rete, governo algoritmico','Regia: Kenji Kamiyama · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_Stand_Alone_Complex_-_Solid_State_Society'),
      'sac-2045':d('Ghost in the Shell: SAC_2045','2020–2022','ONA · 24 episodi','Continuità Stand Alone Complex','Dopo un default globale e la “guerra sostenibile”, la Sezione 9 si ricompone per affrontare i postumani, individui trasformati da un’intelligenza superiore.','Postumani, guerra sostenibile, IA, disuguaglianza','Regia: Kenji Kamiyama e Shinji Aramaki','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_SAC_2045'),
      'sac-2045-film':d('SAC_2045: Sustainable War / The Last Human','2021–2023','2 film compilation','Continuità Stand Alone Complex','I due film condensano e riorganizzano rispettivamente la prima e la seconda stagione di SAC_2045, con scene e montaggio adattati al formato cinematografico.','Postumani, compilazione, guerra, rete','Regia: Michihito Fujii / Kenji Kamiyama / Shinji Aramaki','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_SAC_2045'),
      'ghost-in-the-shell-arise':d('Ghost in the Shell: Arise','2013–2014','OVA · 4 Borders','Continuità Arise','Una Motoko più giovane lascia la 501ª Unità Segreta. Indagini su virus, armi e memorie false la portano a reclutare Batou, Togusa e gli altri futuri membri della Sezione 9.','Origini, memoria, virus, militarizzazione','Regia principale: Kazuchika Kise · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_Arise'),
      'arise-alternative-architecture':d('Arise: Alternative Architecture','2015','Serie TV · 10 episodi','Continuità Arise','Versione televisiva degli OVA Arise in ordine modificato, completata da Pyrophoric Cult, storia inedita che prepara direttamente The New Movie.','Reboot, Fire Starter, cybervirus, origini','Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_Arise'),
      'ghost-in-the-shell-new-movie':d('Ghost in the Shell: The New Movie','2015','Film anime','Continuità Arise','L’assassinio del primo ministro coinvolge Motoko in un complotto legato al progetto 2501 e al virus Fire Starter, consolidando la nascita della Sezione 9.','Politica, origini, memoria, complotto','Regia: Kazuya Nomura · Production I.G','https://en.wikipedia.org/wiki/Ghost_in_the_Shell:_The_New_Movie'),
      'ghost-in-the-shell-2017':d('Ghost in the Shell','2017','Film live action','Continuità live action','Il maggiore Mira Killian scopre che i ricordi con cui è stata costruita nascondono una vita precedente. L’indagine su Kuze mette in discussione la Hanka Robotics.','Identità, memoria, corporazioni, corpo','Regia: Rupert Sanders · Scarlett Johansson','https://en.wikipedia.org/wiki/Ghost_in_the_Shell_(2017_film)'),
      'ghost-in-the-shell-2026':d('The Ghost in the Shell','2026','Serie anime','Nuovo adattamento','Nuovo progetto animato di Science Saru annunciato come ritorno alle radici grafiche e concettuali del manga di Masamune Shirow.','Adattamento, cyberpunk, Sezione 9','Science Saru · regia: Moko-chan','https://en.wikipedia.org/wiki/Ghost_in_the_Shell')
    };
  }

  render() {
    const w=this.work, isGits=this.key.includes('ghost')||this.key.includes('stand')||this.key.includes('sac')||this.key.includes('arise')||this.key==='solid-state-society';
    document.title=`${w.title} — ${isGits?'Ghost in the Shell':'Masamune Shirow'}`;
    this.root.innerHTML=`<section class="border-b border-cyan/20"><div class="mx-auto max-w-6xl px-5 py-16 lg:px-8"><a href="${isGits?'ghost-in-the-shell':'masamune-shirow'}.html" class="font-mono text-xs uppercase tracking-widest text-paper/40 hover:text-cyan">← ${isGits?'Ghost in the Shell':'Masamune Shirow'}</a><div class="mt-14 grid gap-12 lg:grid-cols-[.35fr_1fr]"><div class="grid aspect-[3/4] place-items-center border border-cyan/25 bg-gradient-to-br from-cyan/10 to-violet/10"><span class="font-mono text-7xl font-bold text-cyan/20">${w.title.substring(0,2).toUpperCase()}</span></div><div class="self-center"><p class="font-mono text-xs uppercase tracking-[.3em] text-cyan">${w.year} · ${w.kind}</p><h1 class="mt-5 text-5xl font-semibold leading-[.92] tracking-[-.05em] sm:text-7xl">${w.title}</h1><p class="mt-6 font-mono text-xs uppercase tracking-widest text-lime">${w.continuity}</p><p class="mt-9 max-w-3xl text-xl leading-relaxed text-paper/65">${w.summary}</p></div></div></div></section><section class="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:grid-cols-3 lg:px-8"><div><p class="font-mono text-[10px] uppercase tracking-widest text-paper/35">Crediti</p><p class="mt-3 leading-relaxed">${w.credits}</p></div><div><p class="font-mono text-[10px] uppercase tracking-widest text-paper/35">Temi</p><p class="mt-3 leading-relaxed">${w.themes}</p></div><div><p class="font-mono text-[10px] uppercase tracking-widest text-paper/35">Fonte</p><a href="${w.source}" target="_blank" rel="noopener noreferrer" class="mt-3 block text-cyan hover:text-white">Approfondisci e verifica ↗</a></div></section><section class="border-y border-white/10 bg-white/[.025]"><div class="mx-auto max-w-6xl px-5 py-12 text-paper/45 lg:px-8"><p class="font-mono text-xs uppercase tracking-widest text-cyan">Nota editoriale</p><p class="mt-4 max-w-3xl leading-relaxed">La scheda distingue l’opera e la sua continuità dalle altre reinterpretazioni. Immagini e tavole non vengono ripubblicate in assenza di materiale promozionale chiaramente autorizzato.</p></div></section>`;
  }
}